### ISSUE TITLE
UNABLE to download ccasvsse001-almsivi.bsa

### ISSUE THREAD

**Issue by SkyESV** [Althro/ADT#1]
I followed the instructions and updated to the latest version of skyrim 1611300. downloaded CC content and installed and ran CC and said no to unzip arhive. 
00:04:40.051 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\ccbgssse037-curios.esl)
00:04:40.051 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\ccbgssse037-curios.bsa)
00:04:40.051 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse067-daedinv.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\ccbgssse067-daedinv.bsa)
00:04:40.051 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccasvsse001-almsivi.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\ccasvsse001-almsivi.bsa)
00:04:40.051 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

I have tried many times and re-downloaded CC content but nothing works.

**Comment by Althro** [comment]
Thanks for the report. I think I know what has caused this. I'll aim to get this fixed soon and will let you know once it is 😀

**Comment by Althro** [comment]
@SkyESV This should be fixed in V5.1.3 which I've just released 😄
